default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: ec2-107-20-168-237.compute-1.amazonaws.com
  database: d2qf16dk8rnpts
  username: aveapzhoelqtsm

test:
  <<: *default
  host: dbtest
  database: fourr_test

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-107-20-168-237.compute-1.amazonaws.com
  database: d2qf16dk8rnpts
  username: aveapzhoelqtsm


