default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: fourr_development

test:
  <<: *default
  host: dbtest
  database: fourr_test

# production:
#   adapter: postgis
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>
#   postgis_extension: postgis
#   schema_search_path: public,postgis
#   url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>

