default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: ec2-107-20-168-237.compute-1.amazonaws.com
  database: d2qf16dk8rnpts
  username: aveapzhoelqtsm

test:
  <<: *default
  host: dbtest
  database: fourr_test

production:
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>
  postgis_extension: postgis
  schema_search_path: public,postgis
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>

